import type { Metadata } from 'next';
import Breadcrumb from '@/components/shared/Breadcrumb';
import { siteConfig } from '@/config/site';

export const metadata: Metadata = { title: 'Privacy Policy | NewsPortal', description: `Privacy policy and data protection terms of ${siteConfig.name}.` };

export default function PrivacyPolicyPage() {
  return <main className="max-w-4xl mx-auto px-4 py-8"><Breadcrumb items={[{ label: 'Privacy Policy' }]} /><div className="bg-white dark:bg-gray-900 rounded-2xl p-6 sm:p-10 border border-gray-100 dark:border-gray-800 shadow-sm"><h1 className="text-2xl sm:text-3xl font-black text-gray-900 dark:text-white mb-2">Privacy Policy</h1><p className="text-xs text-gray-400 mb-8">Last Updated: {new Date().toLocaleDateString('hi-IN', { year: 'numeric', month: 'long', day: 'numeric' })}</p><div className="prose dark:prose-invert max-w-none text-sm sm:text-base text-gray-700 dark:text-gray-300 leading-relaxed space-y-6"><section><h2>1. Parichay (Introduction)</h2><p>{siteConfig.name} (&quot;Hum&quot;, &quot;Hamara&quot;) par hum apne pathako ki privacy ka samman karte hain. Ye Privacy Policy batati hai ki jab aap hamari website par aate hain to hum aapki jankari ko kaise collect, use aur protect karte hain.</p></section><section><h2>2. Jankari Jo Hum Collect Karte Hain</h2><p>Hum vyaktigat jankari (jaise Email address) keval tabhi collect karte hain jab aap hamare <strong>Newsletter</strong> ya <strong>Contact Form</strong> ke jariye voluntary roop se use darj karte hain.</p></section><section><h2>3. Cookies aur Web Beacons</h2><p>Hamari website cookies ka upyog karti hai taaki user experience ko behtar banaya ja sake, jaise ki aapki Dark Mode preferences ko yaad rakhna aur anonymous analytics collect karna. Aap apne browser settings ke jariye cookies ko disable kar sakte hain.</p></section><section><h2>4. Third-Party Advertisements (Google AdSense)</h2><p>Hum advertisements dikhane ke liye third-party ad networks jaise Google AdSense ka prayog karte hain. Google DART cookies ka istemal karta hai taaki wo users ko unke internet browsing ke hisab se ads dikha sake. Pathak Google Ad Settings me ja kar personalised ads ko opt-out kar sakte hain.</p></section><section><h2>5. Content &amp; News Aggregation Policy</h2><p>Hamare portal par uplabdh kuch samachar vishleshan publicly available feeds se reference ke taur par taiyar kiye jate hain. Har lekh ke ant me mool srot (source attribution) ka link uplabdh karaya jata hai.</p></section><section><h2>6. Contact Information</h2><p>Agar is policy ke sambandh me aapka koi prashn hai, to aap hamare Grievance Desk par sampark kar sakte hain: <span className="font-semibold text-red-600 block mt-1">support@yourdomain.com</span></p></section></div></div></main>;
}
