import type { Metadata } from 'next';
import Breadcrumb from '@/components/shared/Breadcrumb';
import { siteConfig } from '@/config/site';

export const metadata: Metadata = { title: 'Terms of Service | NewsPortal', description: `Terms and conditions for using ${siteConfig.name}.` };

export default function TermsPage() {
  return <main className="max-w-4xl mx-auto px-4 py-8"><Breadcrumb items={[{ label: 'Terms of Service' }]} /><div className="bg-white dark:bg-gray-900 rounded-2xl p-6 sm:p-10 border border-gray-100 dark:border-gray-800 shadow-sm"><h1 className="text-2xl sm:text-3xl font-black text-gray-900 dark:text-white mb-2">Terms of Service &amp; Disclaimer</h1><p className="text-xs text-gray-400 mb-8">Last Updated: {new Date().toLocaleDateString('hi-IN', { year: 'numeric', month: 'long', day: 'numeric' })}</p><div className="prose dark:prose-invert max-w-none text-sm sm:text-base text-gray-700 dark:text-gray-300 leading-relaxed space-y-6"><section><h2>1. Acceptance of Terms</h2><p>{siteConfig.name} ka upyog karke, aap in sabhi niyamo aur sharton ko sweekar karte hain. Agar aap in sharton se sehmat nahi hain, to kripya website ka prayog na karein.</p></section><section><h2>2. Content &amp; Fair Use Disclaimer</h2><p>Is portal par pradarshit samachar aur lekh informational aur educational uddeshya se publish kiye jate hain. Samachar ke mool copyright unke mul prashak (original publishers) ke paas hain. Hum Fair Use provisions ke tehat summary aur attribution pradan karte hain.</p></section><section><h2>3. Accuracy of Information</h2><p>Hum sabhi tathyo aur samacharo ko verify karne ka pura prayas karte hain, fir bhi kisi anjaane truti ya bazaar parivartan ke liye hamari website utardayi nahi hogi. Pathako se anurodh hai ki mukhya nirnay lene se purva aadhikarik srot ki pushti karein.</p></section><section><h2>4. DMCA &amp; Copyright Grievance Procedure</h2><p>Yadi kisi copyright dharak ko lagta hai ki unki kisi samagri ka anuchit upyog hua hai, to wo hamari grievance team ko direct email bhej sakte hain. Hum 24-48 ghanto ke bheetar us samagri ko verify karke modify ya remove kar denge.</p></section></div></div></main>;
}
